### ISSUE TITLE
include support for bootstrap.py

### ISSUE THREAD

**Issue by psuriset** [redhat-performance/satellite-performance#22]
include support for bootstrap.py in satellite-performance

**Comment by jhutar** [comment]
Agree. This needs to be changed to use bootstrap.py:

playbooks/satellite/roles/client-scripts/files/clients.yaml.j2

**Comment by psuriset** [comment]
https://access.redhat.com/solutions/1233443 Ref

**Comment by jhutar** [comment]
Implemented in 75e637fe71fa17a2a58a67b478ecba18098bbd12
