### ISSUE TITLE
update readme for grafana or graphite install

### ISSUE THREAD

**Issue by jhutar** [redhat-performance/satellite-performance#48]
<sbadhwar> mmccune_afk, We are not using tags anymore for grafana and graphite install
<sbadhwar> ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini ansible/grafana.yaml & ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini ansible/graphite.yaml should work :)

**Comment by h4xr** [comment]
Since, we have migrated the monitoring to a new project(satellite-monitoring), I think, we can close this issue :)
